name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes
          echo "upload_url=$(gh release view "${{ github.ref_name }}" --json uploadUrl -q .uploadUrl)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build (${{ matrix.os }})
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: fortuna-cpu-miner
            asset_name: fortuna-cpu-miner-linux-amd64
            script_name: mine.sh
          - os: windows-latest
            artifact_name: fortuna-cpu-miner.exe
            asset_name: fortuna-cpu-miner-windows-amd64
            script_name: mine.bat
          - os: macos-latest
            artifact_name: fortuna-cpu-miner
            asset_name: fortuna-cpu-miner-macos-amd64
            script_name: mine.sh

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo build --release
      - name: Prepare release package
        shell: bash
        run: |
          mkdir release_package
          cp target/release/${{ matrix.artifact_name }} release_package/
          cp ${{ matrix.script_name }} release_package/
      - name: Zip release package (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path release_package\* -DestinationPath ${{ matrix.asset_name }}.zip
      - name: Zip release package (Unix)
        if: matrix.os != 'windows-latest'
        run: zip -j ${{ matrix.asset_name }}.zip release_package/*
      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" ./${{ matrix.asset_name }}.zip